---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  database: golb
  username: root
  password: 
  log_stream: STDOUT
  log_level: 0
