---
# Edit this file:
development: &defaults
    # These are the settings for repository :default
    adapter:  mysql
    database: golb
    host: localhost
    username: root
    password:
    socket: /opt/local/var/run/mysql5/mysqld.sock
    log_stream: STDOUT
    log_level: 0

test: &defaults
    # These are the settings for repository :default
    database: golb_test
